### ISSUE TITLE
bot uses "admin" db instead of "insurance"

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix/insurance-bot#111]
@l2fprod By default, we're storing the `logs` collection in the `admin` database. If we want to use something like `insurance`, we need to select that db.

I left it to use `admin` in the dashbaord as well until this is fixed.

**Comment by l2fprod** [comment]
What needs to be done here (if anything)? 

The Compose for MongoDB service gives you the connection credentials with admin as default. If you want to switch to another database once connected - and if it is possible to create one in the MongoDB instance through API, why not doing it It is something for you @rvennam and @antonmc to sync on, otherwise just kill this task and we keep it as is.

**Comment by l2fprod** [comment]
no longer needed with Cloudant.
