### ISSUE TITLE
Create a markup HTML and CSS the full flow of the application

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/insurance-bot#12]
I suggest we develop the markup of the full application flow with HTML and CSS and as we build on it we can replace parts of the Markup HTML with working dynamic code. I will tackle this and create the full flow of the project with Markup HTML and CSS.

**Comment by Twanawebtech** [comment]
Anton: Your note reminded me that I had hoped to draw up some UML sequence charts, which have helped with distributed projects I’ve worked on in the past, and are wonderfully helpful for outsiders to understand what we’re up to. How did you envisage describing the flow?

---

Now that I have a good picture whats needed, I would just develop each and every page with static HTML and CSS using dummy data, while the rest of the team completing the other parts of the project and when each part is completes then just replace some of the static code with dynamic code. This is how I would have done other group projects in past with other developers.  As for UML sequence, that would be great also, I will create the pages based on that flow.

**Comment by antonmc** [comment]
Would you mind if we focused on one iteration at a time, rather than the full flow? Every iteration is it’s own product. In the first iteration we want to log in and then see that user’s policy information - the policies they have listed. That’s enough for the first bite I think. In the next bite we want to drill into the policy data some more. So I'd suggest concentrating on that page - how will it look after you log in?

If we want to think long term, I would suggest mapping out some milestones for the future ... and then we can think about the flow related to each milestone. 

The danger of projecting a big long term picture is that we may never get there! Lets see how things shape up after being able to log in and see our policies? What do you think?

**Comment by Twanawebtech** [comment]
Sounds good, I am ok with that, we focus on one iteration at a time so now focus is on user to login via Facebook and see their user policy information.
