### ISSUE TITLE
Provide a way to log in without using facebook

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/insurance-bot#13]
I think lot's of people either don't use facebook, use it only for personal (non-work) stuff or would not want to provide their credentials to log into a demo app. Could we provide a flow that would allow a user to create a username and password instead?

**Comment by antonmc** [comment]
We can add more alternatives in future iterations. Try to think of this as an iterative model. We're not building the final model day one - longer term we can support login in a bunch of ways.

The benefits of using Facebook to begin with:

1] We don't have to develop our own authentication code - so it saves a little time
2] Users in the wider world may be more likely to log in with FB rather than create and forget an account
3] Our message bot will need credentials for Facebook messenger in any case
4] We collect analytics and demographics based on logins via FB's dashboard 
5] We can write a blog post about authenticating with FB, Node and Bluemix
6] FB has 1.6 Billion users ... there's a strong chance people have an account

I'd like to get a working system developed rapidly. We need to start with one mechanism. I'd prefer to use this one. Thoughts?

**Comment by uwefassnacht** [comment]
> We're not building the final model day one

Agree. But I think it might make sense to prioritize the general case (e.g. login with own credentials) over going with FB as a start. Obviously that depends on how much additional work that is.

**Comment by antonmc** [comment]
Have implemented login with Passport js
